{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "exposecontroller.serviceAccountName" . }}
  labels:
{{ include "exposecontroller.labels" . | indent 4 }}
{{- end -}}
